version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running tests..."
      # Uncomment the line below to execute tests
      # - npm test

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Zipping the application..."
      # Zip the entire working directory excluding node_modules
      - zip -r my-react-app.zip . -x "node_modules/*"
      - echo "Artifact zip created."

artifacts:
  files:
    - my-react-app.zip
