version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install dependencies
      - npm install

  pre_build:
    commands:
      # Optional: run tests or other pre-build steps
      # - npm test

  build:
    commands:
      # Build the React app
      - npm run build

  post_build:
    commands:
      # Copy build directory and package.json to a temporary directory
      - mkdir -p /tmp/artifact
      - cp -r build/* /tmp/artifact/
      - cp package.json /tmp/artifact/
      # Include any additional files needed for deployment
      # - cp server.js /tmp/artifact/
      # - cp Procfile /tmp/artifact/
      # Change to the temporary directory and zip the contents
      - cd /tmp/artifact
      - zip -r my-react-app.zip .
      # Move the zip file back to the CodeBuild source directory
      - mv my-react-app.zip $CODEBUILD_SRC_DIR

artifacts:
  files:
    - my-react-app.zip
